package workspace

import (
	"fmt"
	"os"
	"path/filepath"
)

// Manager handles project workspace directories.
// Each project gets its own isolated directory where agent outputs,
// SOPs, docs, and generated code are stored.
type Manager struct {
	BaseDir string // e.g. ~/.mitran/projects/
}

func New(baseDir string) (*Manager, error) {
	if err := os.MkdirAll(baseDir, 0755); err != nil {
		return nil, fmt.Errorf("create base dir: %w", err)
	}
	return &Manager{BaseDir: baseDir}, nil
}

// Init creates the full project workspace structure.
func (m *Manager) Init(projectID, projectName string) (string, error) {
	dir := filepath.Join(m.BaseDir, projectID)
	dirs := []string{
		dir,
		filepath.Join(dir, "src"),
		filepath.Join(dir, "docs"),
		filepath.Join(dir, "docs", "api"),
		filepath.Join(dir, "docs", "architecture"),
		filepath.Join(dir, "wiki"),
		filepath.Join(dir, "sops"),
		filepath.Join(dir, "monitoring"),
		filepath.Join(dir, "monitoring", "dashboards"),
		filepath.Join(dir, "monitoring", "alerts"),
		filepath.Join(dir, "cicd"),
		filepath.Join(dir, "tickets"),
		filepath.Join(dir, "hr"),
		filepath.Join(dir, ".mitran"),
	}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0755); err != nil {
			return "", fmt.Errorf("create %s: %w", d, err)
		}
	}

	// Write project context file (agents read this for project awareness)
	ctx := fmt.Sprintf(`# Project: %s
ID: %s
Created: auto-generated by mitran init

## Structure
- src/          — Source code and scaffolding
- docs/         — Technical documentation (HLD, LLD, API, runbooks)
- wiki/         — Knowledge base pages
- sops/         — Standard Operating Procedures
- monitoring/   — Grafana dashboards + Prometheus alert rules
- cicd/         — Pipeline configs, deploy scripts, env files
- tickets/      — Sprint templates, backlog exports
- hr/           — Onboarding checklists, PTO policies
- .mitran/      — Internal metadata (agent history, checkpoints)
`, projectName, projectID)

	if err := os.WriteFile(filepath.Join(dir, ".mitran", "context.md"), []byte(ctx), 0644); err != nil {
		return "", err
	}

	return dir, nil
}

// Path returns the workspace root for a project.
func (m *Manager) Path(projectID string) string {
	return filepath.Join(m.BaseDir, projectID)
}

// SubPath returns a specific path within a project workspace.
func (m *Manager) SubPath(projectID, sub string) string {
	return filepath.Join(m.BaseDir, projectID, sub)
}

// Exists checks if a project workspace has been initialized.
func (m *Manager) Exists(projectID string) bool {
	_, err := os.Stat(filepath.Join(m.BaseDir, projectID, ".mitran", "context.md"))
	return err == nil
}

// WriteFile writes content to a path within the project workspace.
func (m *Manager) WriteFile(projectID, relativePath, content string) error {
	full := filepath.Join(m.BaseDir, projectID, relativePath)
	if err := os.MkdirAll(filepath.Dir(full), 0755); err != nil {
		return err
	}
	return os.WriteFile(full, []byte(content), 0644)
}

// ReadFile reads a file from the project workspace.
func (m *Manager) ReadFile(projectID, relativePath string) (string, error) {
	data, err := os.ReadFile(filepath.Join(m.BaseDir, projectID, relativePath))
	return string(data), err
}

// ListFiles lists files in a subdirectory of the project workspace.
func (m *Manager) ListFiles(projectID, subDir string) ([]string, error) {
	dir := filepath.Join(m.BaseDir, projectID, subDir)
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var files []string
	for _, e := range entries {
		if !e.IsDir() {
			files = append(files, e.Name())
		}
	}
	return files, nil
}
