"""Dev Agent v2 - Creates real GitHub PRs with generated code."""
import logging
from worker.agents.dev_agent import BaseAgent, AgentResult, FileChange
from worker.integrations.github import (
    create_repo, create_branch, create_pull_request,
    create_workflow_file, GitHubAPIError
)
from worker.llm import invoke as llm_invoke

log = logging.getLogger(__name__)

class DevAgentV2(BaseAgent):
    agent_type = 'dev'
    system_prompt = """You are a senior software engineer. Generate production-quality code.
    When given a task:
    1. Plan the file structure
    2. Write each file with proper imports, error handling, tests
    3. Include a README.md explaining the implementation
    4. Follow the project's language conventions
    Output each file as: === FILE: path/to/file ===\n<content>\n=== END ==="""

    def execute(self, task_description: str, context: dict) -> AgentResult:
        project = context.get('project_name', 'unknown')
        languages = context.get('languages', ['Python'])
        workspace = context.get('workspace_path', '')

        prompt = f"""Project: {project}
Languages: {', '.join(languages) if isinstance(languages, list) else languages}
Task: {task_description}

Generate production-quality code files."""

        response = self._call_llm(prompt)
        files = self._parse_files(response)

        # Try to create GitHub PR if configured
        pr_url = None
        github_org = context.get('github_org', '')
        github_repo = context.get('github_repo', '')

        if github_org and github_repo:
            try:
                branch = f'mitran/agent-{context.get("task_id", "dev")[:8]}'
                create_branch(github_org, github_repo, branch)
                for f in files:
                    create_workflow_file(github_org, github_repo, f.content, f.path)
                pr = create_pull_request(
                    github_org, github_repo,
                    title=f'[Mitran] {task_description[:60]}',
                    body=f'Auto-generated by Mitran Dev Agent\n\nTask: {task_description}',
                    head=branch
                )
                pr_url = pr.get('html_url', '')
                log.info(f'Created PR: {pr_url}')
            except GitHubAPIError as e:
                log.warning(f'GitHub PR creation failed: {e}')

        summary = f'## Dev Agent Output\n\nGenerated {len(files)} files'
        if pr_url:
            summary += f'\n\n**PR:** {pr_url}'
        summary += f'\n\n### Files\n' + '\n'.join(f'- `{f.path}`' for f in files)

        return AgentResult(summary=summary, files=files)

    def _parse_files(self, response: str) -> list[FileChange]:
        files = []
        parts = response.split('=== FILE: ')
        for part in parts[1:]:
            lines = part.split('\n')
            path = lines[0].strip().rstrip(' =').strip()
            content_lines = []
            for line in lines[1:]:
                if line.strip().startswith('=== END'):
                    break
                content_lines.append(line)
            content = '\n'.join(content_lines)
            files.append(FileChange(path=path, action='create', content=content))
        if not files and response.strip():
            files.append(FileChange(path='output.txt', action='create', content=response))
        return files
