apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mitran.fullname" . }}-engine
  labels:
    {{- include "mitran.labels" . | nindent 4 }}
    app.kubernetes.io/component: engine
spec:
  replicas: {{ .Values.engine.replicas }}
  selector:
    matchLabels:
      {{- include "mitran.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: engine
  template:
    metadata:
      labels:
        {{- include "mitran.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: engine
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: engine
          image: "{{ .Values.engine.image.repository }}:{{ .Values.engine.image.tag }}"
          imagePullPolicy: {{ .Values.engine.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.engine.port }}
              protocol: TCP
          {{- with .Values.engine.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.engine.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.engine.port }}
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.engine.port }}
            initialDelaySeconds: 3
